language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

before_script:
  - jdk_switcher use oraclejdk8

#r_packages:
#  - rJava

dist: trusty

addons:
  apt:
    packages:
      - oracle-java8-installer
